---
- id: 1
  name: keppler_default
  active: true
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2019-02-04 15:44:00.281580000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2019-02-04 11:44:00.281580000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2019-02-04 15:44:00.281580000 Z
    zone: *1
    time: 2019-02-04 11:44:00.281580000 Z
