menu:
  keppler_banners:
    name: Banners
    current: ['/']
    url_path: /
    icon: rocket
    model: User
    environment: all
    submenu:
      - banner:
          name: banner
          url_path: /admin/banners/banners
          icon: layers
          current: ['/admin/banners/banners']
          model: KepplerBanners::Banner

      # - new:
      #     name: + Add new module
      #     url_path: /url_path
      #     current: ['/current_path']
      #     enviroment: development
      #     model: User